USE CGV;
-- 예매한 영화이름, 영화관, 좌석이름, 아이디, 상영일, 상영시간를 조회하는 뷰생성
CREATE VIEW TICKET_DETAIL1
AS
SELECT MO_TITLE, SS_DATE, SS_TIME, CI_NAME,SE_NAME,TI_ME_ID FROM TICKETING 
	JOIN TICKETING_SEAT ON TS_TI_NUM = TI_NUM
    JOIN SEAT ON SE_NUM = TS_SE_NUM
    JOIN SCREEN_SCHEDULE ON SS_NUM = TI_SS_NUM
    JOIN MOVIE ON MO_NUM = SS_MO_NUM
    JOIN CINEMA ON CI_NUM = SS_CI_NUM;
SELECT*FROM TICKET_DETAIL1;

CREATE VIEW TICKET_DETAIL2
AS
SELECT * FROM TICKETING 
	JOIN TICKETING_SEAT ON TS_TI_NUM = TI_NUM
    JOIN SEAT ON SE_NUM = TS_SE_NUM
    JOIN SCREEN_SCHEDULE ON SS_NUM = TI_SS_NUM
    JOIN MOVIE ON MO_NUM = SS_MO_NUM
    JOIN CINEMA ON CI_NUM = SS_CI_NUM;
SELECT*FROM TICKET_DETAIL2;

-- ABC회원이 영화 예매를 위해 사용한 금액은?
SELECT SUM(SE_PRICE) `예매금액` FROM TICKET_DETAIL2;