-- 예매를 하면, 해당 영화상영시간의 예매 가능 좌석을 수정해주는 트리거를 생성하고, 테스트
USE CGV;
DROP TRIGGER IF EXISTS INSERT_TICKETING;
DELIMITER //
CREATE TRIGGER INSERT_TICKETING AFTER INSERT 
ON TICKETING
FOR EACH ROW
BEGIN
	UPDATE SCREEN_SCHEDULE
		SET SS_POSSIBLE_SEAT = SS_POSSIBLE_SEAT - NEW.TI_AMOUNT
        WHERE SS_NUM = NEW.TI_SS_NUM;
END //
DELIMITER ;

INSERT INTO TICKETING(TI_AMOUNT, TI_TOTAL_PRICE,TI_ME_ID,TI_SS_NUM)
	VALUES(1,10000,'abc',26);