CREATE TABLE `STUDENT` (
	`ST_NUM`	VARCHAR(15)	NOT NULL,
	`ST_NAME`	VARCHAR(20)	NULL,
	`ST_SEMESTER`	INT NOT NULL DEFAULT 1	NULL,
	`ST_STATE`	VARCHAR(10) NOT NULL '재학'	NULL	DEFAULT '재학',
	`ST_PR_NUM`	INT	NOT NULL
);

CREATE TABLE `DEPARTEMENT` (
	`DE_NUM`	CHAR(3)	NOT NULL,
	`DE_NAME`	VACHAR(20)	NULL,
	`DE_ADDRESS`	VARCHAR(50)	NULL,
	`DE_TEL`	VARCHAR(13)	NULL,
	`DE_PR_NUM`	CHAR(10)	NOT NULL
);

CREATE TABLE `SCORE` (
	`SC_NUM`	INT AUTO_INCREMENT	NOT NULL,
	`SC_MID`	INT NOT NULL DEFAULT 0	NULL,
	`SC_FINAL`	INT NOT NULL DEFAULT 0	NULL,
	`SC_HOMEWORK`	INT NOT NULL DEFAULT 0	NULL,
	`SC_ATTENDANCE`	INT NOT NULL DEFAULT 0	NULL,
	`SC_TOTAL`	INT NOT NULL DEFAULT 0	NULL,
	`SC_CO_NUM`	INT	NOT NULL
);

CREATE TABLE `PROFESSOR` (
	`PR_NUM`	CHAR(10)	NOT NULL,
	`PR_NAME`	VARCHAR(20)	NULL,
	`PR_STATE`	VARCHAR(10)	NULL,
	`PR_DE_NUM`	CHAR(3)	NOT NULL,
	`PR_TEL`	VARCHAR(13)	NULL
);

CREATE TABLE `LECTURE` (
	`LE_NUM`	INT AUTO_INCREMENT	NOT NULL,
	`LE_NAME`	VARCHAR(30)	NULL,
	`LE_SCHEDULE`	VARCHAR(50)	NULL,
	`LE_POINT`	INT	NULL,
	`LE_CLASS`	INT	NULL,
	`LE_YEAR`	INT	NULL,
	`LE_TERM`	INT	NULL,
	`LE_PR_NUM`	CHAR(10)	NOT NULL
);

CREATE TABLE `COURSE` (
	`CO_NUM`	INT AUTO_INCREMENT	NOT NULL,
	`CO_ST_NUM`	VARCHAR(15)	NOT NULL,
	`CO_LE_NUM`	INT	NOT NULL,
	`CO_TYPE`	CARCHAR(5)	NULL,
	`CO_GRADE`	VARCHAR(3)	NULL
);

CREATE TABLE `MOJOR` (
	`MO_NUM`	INT AUTO_INCREMENT	NOT NULL,
	`MO_ST_NUM`	VARCHAR(15)	NOT NULL,
	`MO_DE_NUM`	CHAR(3)	NOT NULL,
	`MO_STATE`	VARCHAR(10)	NULL
);

ALTER TABLE `STUDENT` ADD CONSTRAINT `PK_STUDENT` PRIMARY KEY (
	`ST_NUM`
);

ALTER TABLE `DEPARTEMENT` ADD CONSTRAINT `PK_DEPARTEMENT` PRIMARY KEY (
	`DE_NUM`
);

ALTER TABLE `SCORE` ADD CONSTRAINT `PK_SCORE` PRIMARY KEY (
	`SC_NUM`
);

ALTER TABLE `PROFESSOR` ADD CONSTRAINT `PK_PROFESSOR` PRIMARY KEY (
	`PR_NUM`
);

ALTER TABLE `LECTURE` ADD CONSTRAINT `PK_LECTURE` PRIMARY KEY (
	`LE_NUM`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `PK_COURSE` PRIMARY KEY (
	`CO_NUM`
);

ALTER TABLE `MOJOR` ADD CONSTRAINT `PK_MOJOR` PRIMARY KEY (
	`MO_NUM`
);

ALTER TABLE `STUDENT` ADD CONSTRAINT `FK_PROFESSOR_TO_STUDENT_1` FOREIGN KEY (
	`ST_PR_NUM`
)
REFERENCES `PROFESSOR` (
	`PR_NUM`
);

ALTER TABLE `DEPARTEMENT` ADD CONSTRAINT `FK_PROFESSOR_TO_DEPARTEMENT_1` FOREIGN KEY (
	`DE_PR_NUM`
)
REFERENCES `PROFESSOR` (
	`PR_NUM`
);

ALTER TABLE `SCORE` ADD CONSTRAINT `FK_COURSE_TO_SCORE_1` FOREIGN KEY (
	`SC_CO_NUM`
)
REFERENCES `COURSE` (
	`CO_NUM`
);

ALTER TABLE `PROFESSOR` ADD CONSTRAINT `FK_DEPARTEMENT_TO_PROFESSOR_1` FOREIGN KEY (
	`PR_DE_NUM`
)
REFERENCES `DEPARTEMENT` (
	`DE_NUM`
);

ALTER TABLE `LECTURE` ADD CONSTRAINT `FK_PROFESSOR_TO_LECTURE_1` FOREIGN KEY (
	`LE_PR_NUM`
)
REFERENCES `PROFESSOR` (
	`PR_NUM`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `FK_STUDENT_TO_COURSE_1` FOREIGN KEY (
	`CO_ST_NUM`
)
REFERENCES `STUDENT` (
	`ST_NUM`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `FK_LECTURE_TO_COURSE_1` FOREIGN KEY (
	`CO_LE_NUM`
)
REFERENCES `LECTURE` (
	`LE_NUM`
);

ALTER TABLE `MOJOR` ADD CONSTRAINT `FK_STUDENT_TO_MOJOR_1` FOREIGN KEY (
	`MO_ST_NUM`
)
REFERENCES `STUDENT` (
	`ST_NUM`
);

ALTER TABLE `MOJOR` ADD CONSTRAINT `FK_DEPARTEMENT_TO_MOJOR_1` FOREIGN KEY (
	`MO_DE_NUM`
)
REFERENCES `DEPARTEMENT` (
	`DE_NUM`
);

